name: Update Readme with Topic Info

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic to search and update in README'
        required: true
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install feedparser node-fetch

      - name: Run update script
        run: |
          topic="${{ github.event.inputs.topic }}"
          node ./scripts/update_readme.js "${topic}"

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with new topic information: ${{ github.event.inputs.topic }}" && git push)