name: Update Readme with Topic Info

on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic to search and update in README'
        required: true
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  update_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v20.12.1'

      - name: Install dependencies
        run: |
          npm init -y
          npm install node-fetch@2

      - name: Search and fetch information
        id: search
        run: |
          node << EOF
          const fetch = require('node-fetch');

          async function searchGoogle(query) {
            const encodedQuery = encodeURIComponent(query);
            const url = \`https://en.wikipedia.org/w/api.php?action=query&format=json&prop=extracts&exintro=1&explaintext=1&titles=\${encodedQuery}\`;            
            try {
              const response = await fetch(url);
              const data = await response.json();
              const pages = data.query.pages;
              const pageId = Object.keys(pages)[0];
              const extract = pages[pageId].extract;

              if (extract) {
                return extract.split('\n')[0]; // Return only the first paragraph
              } else {
                return "No information found for this topic.";
              }
            } catch (error) {
              console.error('Error searching:', error);
              return "An error occurred while fetching information.";
            }
          }

          searchGoogle("${{ github.event.inputs.topic }}")
            .then(result => {
              console.log("info<<EOF");
              console.log(result);
              console.log("EOF");
            })
            .catch(error => {
              console.error(error);
              process.exit(1);
            });
          EOF

      - name: Run search and update script
        run: node ./scripts/read.js "${{ github.event.inputs.topic }}" "${{ steps.search.outputs.info }}"

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with new topic information: ${{ github.event.inputs.topic }}" && git push)